### ISSUE TITLE
/sakibc/Prusa-Firmware-RAMPS

### ISSUE THREAD

**Issue by boelle** [sakibc/hello-world#3]
Hi and sorry for the instrusion but i have 2 questions

1) will you update this when prusa updates?
2) how "easy" would it be to add support for the full graphic LCD's? i'm not after some fancy graphics but just to recycle what i allready have, so 2 (or is it 4?) lines of text on the graphic display is fine with me

**Comment by sakibc** [comment]
Hi,

1. Seeing as Prusa is no longer releasing updates to the MK2 firmware and have moved on to the MK2.5/MK3 firmware, I don't expect to be updating this beyond features I decide to backport from Marlin myself. Sorry about that.

2. I attempted to get a full graphic LCD working with this firmware a while back, and decided it was not worth the effort. Prusa has made extensive changes to the standard LCD code that have not been made to the full graphic LCD code, meaning it's not as simple as disabling one and enabling the other like in Marlin. I'd recommend either sticking with Marlin or purchasing a standard LCD, which I have seen available at various places for $20.

Hope I've answered your questions.

**Comment by boelle** [comment]
yep... i think i have  to bite the bullet on the lcd

i'm taking a try on their mk3 branch and basing things off the einsy config.... got almost all the pins corrected to that of a Ramps board

but i still need to judge if it makes sense as i would need to fabricate a small addon that allows me to connect the filament sensor and power panic... i got the source files for those 2 so i can fabricate them also

but thanks for the reply... will give  shout if i ever get it to work and its not overly expensice
