### ISSUE TITLE
sorry for bad use 

### ISSUE THREAD

**Issue by boelle** [sakibc/hello-world#4]
Hi, i wonder if you will update the prusa firmware to latest version?
and are there a reson to do so?

**Comment by sakibc** [comment]
Hi there,

I will not be updating the firmware, as I'm no longer using RAMPS or the Prusa firmware for my 3D printer. Sorry about that.

**Comment by boelle** [comment]
no worries, i managed to update to 3.2.3 which is the latest for the mk2
it took some carefull hands but it compiles and i can talk to it over serial, just need to get a display and build a small test setup
